---
Name: focuspoint
---
SilverStripe\Assets\Image:
  extensions:
    - SilverStripeFocusPoint\FocusPointImage

#SilverStripeFocusPoint\FocusPointField:
#  debug: true
#   max_width: 500
#   max_height: 300

# Injector:
#   Image:
#     class: FPImage
#   Image_Cached:
#     class: FPImage_Cached
#   ImagickBackend:
#     class: "FPImagickBackend"
